import asyncio
import base64
import io
import json
import logging
import os
import re
import secrets
import time
import uuid
import zipfile
from pathlib import Path
from typing import Any

import discord
from discord import app_commands
from discord.ext import commands
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent
ENV_FILE = ROOT / ".env"
DATA_FILE = ROOT / "forge_data.json"

if not ENV_FILE.exists():
    ENV_FILE.write_text(
        "# ESN Forge configuration\nDISCORD_TOKEN=\nOWNER_IDS=\nOPENAI_API_KEY=\nOPENAI_MODEL=gpt-5.6-luna\n",
        encoding="utf-8",
    )
load_dotenv(ENV_FILE)

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(name)s | %(message)s")
log = logging.getLogger("esn-forge")
TOKEN = os.getenv("DISCORD_TOKEN", "").strip()
if not TOKEN:
    raise RuntimeError("DISCORD_TOKEN is missing. Forge created .env; add your bot token and restart.")


def owners() -> set[int]:
    return {int(x.strip()) for x in os.getenv("OWNER_IDS", "").split(",") if x.strip().isdigit()}


def clean_name(value: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9._-]+", "-", value.strip())
    return value.strip(".-_")[:48] or "forge-project"


def hex_color(value: str) -> int:
    value = value.strip().lstrip("#")
    if not re.fullmatch(r"[0-9a-fA-F]{6}", value):
        raise ValueError("Color must be a 6-digit hex value such as #42E8F4.")
    return int(value, 16)


def save_state(data: dict[str, Any]) -> None:
    tmp = DATA_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(data, indent=2), encoding="utf-8")
    tmp.replace(DATA_FILE)


def load_state() -> dict[str, Any]:
    if not DATA_FILE.exists():
        return {"guilds": {}, "usage": {}}
    try:
        return json.loads(DATA_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"guilds": {}, "usage": {}}


STATE = load_state()
HISTORY: dict[int, list[dict[str, str]]] = {}
COOLDOWN: dict[tuple[int, str], float] = {}


def guild_state(guild_id: int) -> dict[str, Any]:
    key = str(guild_id)
    STATE.setdefault("guilds", {}).setdefault(key, {"ai_enabled": True, "model": os.getenv("OPENAI_MODEL", "gpt-5.6-luna")})
    return STATE["guilds"][key]


def usage(user_id: int) -> None:
    key = str(user_id)
    STATE.setdefault("usage", {}).setdefault(key, 0)
    STATE["usage"][key] += 1
    save_state(STATE)


def allowed(interaction: discord.Interaction, seconds: float = 5.0) -> bool:
    key = (interaction.user.id, interaction.command.name if interaction.command else "unknown")
    now = time.monotonic()
    if now - COOLDOWN.get(key, 0) < seconds:
        return False
    COOLDOWN[key] = now
    return True


def project_files(name: str, language: str, features: list[str]) -> dict[str, str]:
    name = clean_name(name)
    feature_text = ", ".join(features) if features else "ping"
    if language == "javascript":
        return {
            "index.js": '''const { Client, GatewayIntentBits } = require("discord.js");\nrequire("dotenv").config();\n\nconst client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages] });\nclient.once("ready", () => console.log(`Logged in as ${client.user.tag}`));\nclient.on("interactionCreate", async interaction => {\n  if (!interaction.isChatInputCommand()) return;\n  if (interaction.commandName === "ping") await interaction.reply(`Pong! ${client.ws.ping}ms`);\n});\nclient.login(process.env.DISCORD_TOKEN);\n''',
            "package.json": json.dumps({"name": name.lower().replace("_", "-"), "version": "1.0.0", "main": "index.js", "scripts": {"start": "node index.js"}, "dependencies": {"discord.js": "^14.16.0", "dotenv": "^16.4.5"}}, indent=2),
            ".env.example": "DISCORD_TOKEN=\n",
            ".gitignore": ".env\nnode_modules/\n",
            "README.md": f"# {name}\n\nDiscord.js starter generated by ESN Forge.\n\nFeatures requested: {feature_text}\n\n1. Copy `.env.example` to `.env`.\n2. Add your Discord bot token.\n3. Run `npm install` then `npm start`.\n",
        }
    return {
        "bot.py": '''import os\nimport discord\nfrom discord import app_commands\nfrom discord.ext import commands\nfrom dotenv import load_dotenv\n\nload_dotenv()\nTOKEN = os.getenv("DISCORD_TOKEN")\nintents = discord.Intents.default()\nbot = commands.Bot(command_prefix="!", intents=intents)\n\n@bot.event\nasync def on_ready():\n    await bot.tree.sync()\n    print(f"Online as {bot.user}")\n\n@bot.tree.command(name="ping", description="Check bot latency")\nasync def ping(interaction: discord.Interaction):\n    await interaction.response.send_message(f"Pong! {round(bot.latency * 1000)}ms")\n\nbot.run(TOKEN)\n''',
        "requirements.txt": "discord.py>=2.5,<3\npython-dotenv>=1.0,<2\n",
        ".env.example": "DISCORD_TOKEN=\n",
        ".gitignore": ".env\n__pycache__/\n*.pyc\n",
        "README.md": f"# {name}\n\nDiscord.py starter generated by ESN Forge.\n\nFeatures requested: {feature_text}\n\n1. Copy `.env.example` to `.env`.\n2. Add your Discord bot token.\n3. Install requirements and run `python bot.py`.\n",
    }


def make_zip(files: dict[str, str], root: str) -> io.BytesIO:
    stream = io.BytesIO()
    with zipfile.ZipFile(stream, "w", zipfile.ZIP_DEFLATED) as archive:
        for path, content in files.items():
            archive.writestr(f"{root}/{path}", content)
    stream.seek(0)
    return stream


def ast_review(code: str) -> list[str]:
    import ast
    findings: list[str] = []
    try:
        tree = ast.parse(code)
    except SyntaxError as exc:
        return [f"Syntax error on line {exc.lineno}: {exc.msg}"]
    dangerous = {"eval", "exec", "compile", "__import__"}
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id in dangerous:
            findings.append(f"Line {node.lineno}: avoid {node.func.id}() on untrusted input.")
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr == "run":
            findings.append(f"Line {node.lineno}: review subprocess/process execution carefully.")
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            if re.search(r"(?:token|api[_-]?key|password|secret)\\s*[=:]\\s*['\"]", node.value, re.I):
                findings.append(f"Line {node.lineno}: possible hard-coded secret; move it to environment variables.")
    if not findings:
        findings.append("No obvious Python AST/security issues found. Add tests and validate external inputs.")
    return findings[:12]


async def ask_openai(prompt: str, guild_id: int | None = None) -> str:
    key = os.getenv("OPENAI_API_KEY", "").strip()
    if not key:
        return "OpenAI is not configured yet. Add OPENAI_API_KEY to .env and restart Forge."
    try:
        from openai import AsyncOpenAI
        client = AsyncOpenAI(api_key=key)
        model = os.getenv("OPENAI_MODEL", "gpt-5.6-luna")
        if guild_id:
            model = guild_state(guild_id).get("model") or model
        response = await client.responses.create(
            model=model,
            instructions="You are ESN Forge, a senior software engineer. Give concrete, safe, production-minded answers. Never expose or request secrets. When asked to generate code, provide complete runnable code rather than TODO placeholders.",
            input=prompt,
        )
        return response.output_text[:7000]
    except Exception as exc:
        log.exception("OpenAI request failed")
        return f"AI request failed: {type(exc).__name__}. Check OPENAI_MODEL, API access, and your key."


intents = discord.Intents.default()
intents.message_content = True
intents.members = True


class Forge(commands.Bot):
    def __init__(self):
        super().__init__(command_prefix="!", intents=intents, help_command=None)

    async def setup_hook(self):
        synced = await self.tree.sync()
        log.info("Synced %s application commands", len(synced))

    async def on_ready(self):
        log.info("ESN Forge online as %s in %s guilds", self.user, len(self.guilds))
        await self.change_presence(activity=discord.Game(name="/forge • Build. Create. Deploy."))


bot = Forge()


@bot.tree.command(name="forge", description="Open the ESN Forge command hub.")
async def forge(interaction: discord.Interaction):
    embed = discord.Embed(title="⚒️ ESN Forge", description="**Build. Create. Deploy.**\n\nYour all-in-one coding, bot, server, embed, and AI toolkit.", color=0x42E8F4)
    embed.add_field(name="🤖 AI", value="`/ask` ` /code` `/debug` `/review` `/improve` `/convert`", inline=False)
    embed.add_field(name="🧩 Builders", value="`/bot` `/project` `/server` `/embed`", inline=False)
    embed.add_field(name="🛠️ Tools", value="`/color` `/base64` `/uuid` `/regex` `/timestamp` `/health`", inline=False)
    await interaction.response.send_message(embed=embed)


@bot.tree.command(name="help", description="Show every major ESN Forge command.")
async def help_command(interaction: discord.Interaction):
    text = ("**AI:** `/ask` `/code` `/debug` `/review` `/improve` `/convert`\n"
            "**Build:** `/bot` `/project` `/server` `/embed`\n"
            "**Utility:** `/color` `/base64` `/uuid` `/regex` `/timestamp` `/health` `/stats`\n"
            "**Admin:** `/config` `/deploy-check` `/shutdown`\n\nAll generated projects are downloadable ZIP files and contain no secrets.")
    await interaction.response.send_message(text, ephemeral=True)


@bot.tree.command(name="ping", description="Check Forge latency.")
async def ping(interaction: discord.Interaction):
    await interaction.response.send_message(f"🏓 Pong — {round(bot.latency * 1000)}ms")


@bot.tree.command(name="ask", description="Ask the ESN Forge AI assistant.")
@app_commands.describe(prompt="Your coding or project question")
async def ask(interaction: discord.Interaction, prompt: str):
    if not allowed(interaction):
        await interaction.response.send_message("⏳ Slow down for a moment.", ephemeral=True); return
    if interaction.guild and not guild_state(interaction.guild.id).get("ai_enabled", True):
        await interaction.response.send_message("AI is disabled for this server.", ephemeral=True); return
    await interaction.response.defer()
    usage(interaction.user.id)
    answer = await ask_openai(prompt, interaction.guild_id)
    HISTORY.setdefault(interaction.user.id, []).append({"q": prompt, "a": answer})
    HISTORY[interaction.user.id] = HISTORY[interaction.user.id][-8:]
    await interaction.followup.send(answer[:1900])


async def ai_task(interaction: discord.Interaction, instruction: str):
    if not allowed(interaction):
        await interaction.response.send_message("⏳ Slow down for a moment.", ephemeral=True); return
    await interaction.response.defer()
    usage(interaction.user.id)
    await interaction.followup.send((await ask_openai(instruction, interaction.guild_id))[:1900])


@bot.tree.command(name="code", description="Generate or explain code.")
@app_commands.describe(request="What code do you need?")
async def code(interaction: discord.Interaction, request: str):
    await ai_task(interaction, f"Write complete code for this request:\n{request}")


@bot.tree.command(name="debug", description="Diagnose an error and give a concrete fix.")
@app_commands.describe(error="Error message and relevant code")
async def debug(interaction: discord.Interaction, error: str):
    await ai_task(interaction, f"Debug this. Identify root cause, exact fix, and corrected code where useful:\n{error}")


@bot.tree.command(name="review", description="Review Python code for correctness and security.")
@app_commands.describe(code_text="Python source code")
async def review(interaction: discord.Interaction, code_text: str):
    findings = ast_review(code_text)
    await interaction.response.send_message("**Python review**\n" + "\n".join(f"• {x}" for x in findings), ephemeral=True)


@bot.tree.command(name="improve", description="Get concrete improvement recommendations for code.")
@app_commands.describe(code_text="Code to improve")
async def improve(interaction: discord.Interaction, code_text: str):
    await ai_task(interaction, f"Review this code and propose concrete improvements. Return prioritized fixes and improved snippets:\n{code_text}")


@bot.tree.command(name="convert", description="Convert code between languages or frameworks.")
@app_commands.describe(code_text="Source code", target="Target language/framework")
async def convert(interaction: discord.Interaction, code_text: str, target: str):
    await ai_task(interaction, f"Convert this code to {target}. Preserve behavior and return complete runnable code:\n{code_text}")


@bot.tree.command(name="bot", description="Generate a downloadable Discord bot project.")
@app_commands.describe(name="Project name", language="python or javascript", features="Comma-separated features")
async def create(interaction: discord.Interaction, name: str, language: str = "python", features: str = "ping,help"):
    language = language.lower().strip()
    if language not in {"python", "javascript", "js", "node"}:
        await interaction.response.send_message("Language must be `python` or `javascript`.", ephemeral=True); return
    language = "javascript" if language in {"javascript", "js", "node"} else "python"
    feature_list = [x.strip() for x in features.split(",") if x.strip()][:20]
    files = project_files(name, language, feature_list)
    stream = make_zip(files, clean_name(name))
    await interaction.response.send_message(content=f"⚒️ Generated **{clean_name(name)}** ({language}) with {len(files)} files.", file=discord.File(stream, filename=f"{clean_name(name)}.zip"))


@bot.tree.command(name="project", description="Generate a project blueprint and starter files.")
@app_commands.describe(name="Project name", description="What should the project do?", language="python or javascript")
async def project(interaction: discord.Interaction, name: str, description: str, language: str = "python"):
    files = project_files(name, "javascript" if language.lower() in {"javascript", "js", "node"} else "python", [description])
    stream = make_zip(files, clean_name(name))
    await interaction.response.send_message(content=f"📦 Project **{clean_name(name)}** generated from your specification.", file=discord.File(stream, filename=f"{clean_name(name)}.zip"))


@bot.tree.command(name="embed", description="Build and preview a Discord embed.")
@app_commands.describe(title="Embed title", description="Embed description", color="Hex color", footer="Footer text", url="Optional URL")
async def embed(interaction: discord.Interaction, title: str, description: str, color: str = "42E8F4", footer: str = "ESN Forge", url: str = ""):
    try:
        value = hex_color(color)
    except ValueError as exc:
        await interaction.response.send_message(str(exc), ephemeral=True); return
    obj = discord.Embed(title=title[:256], description=description[:4096], color=value, url=url[:2000] if url else discord.Embed.Empty)
    if footer: obj.set_footer(text=footer[:2048])
    data = {"title": title, "description": description, "color": value, "footer": footer, "url": url}
    await interaction.response.send_message(embed=obj)
    await interaction.followup.send("```json\n" + json.dumps(data, indent=2)[:1800] + "\n```", ephemeral=True)


@bot.tree.command(name="server", description="Create a safe server blueprint.")
@app_commands.describe(style="community, gaming, or creator")
async def plan_server(interaction: discord.Interaction, style: str = "gaming"):
    style = style.lower()
    presets = {
        "community": ["WELCOME", "INFO", "GENERAL", "COMMUNITY", "VOICE", "STAFF"],
        "gaming": ["WELCOME", "INFO", "GENERAL", "GAMING", "MATCHMAKING", "VOICE", "STAFF"],
        "creator": ["WELCOME", "ANNOUNCEMENTS", "CONTENT", "COMMUNITY", "COLLABS", "VOICE", "STAFF"],
    }
    channels = presets.get(style, presets["gaming"])
    roles = ["Owner", "Admin", "Moderator", "Staff", "Member"]
    embed = discord.Embed(title=f"🏗️ {style.title()} Server Blueprint", color=0x42E8F4)
    embed.add_field(name="Categories", value="\n".join(f"• {x}" for x in channels), inline=True)
    embed.add_field(name="Roles", value="\n".join(f"• {x}" for x in roles), inline=True)
    embed.set_footer(text="Blueprint only — existing channels and roles are never deleted by Forge.")
    await interaction.response.send_message(embed=embed)


@bot.tree.command(name="config", description="Configure Forge for this server.")
@app_commands.describe(ai_enabled="Enable or disable AI commands")
async def config(interaction: discord.Interaction, ai_enabled: bool):
    if not interaction.user.guild_permissions.manage_guild and interaction.user.id not in owners():
        await interaction.response.send_message("You need Manage Server permission.", ephemeral=True); return
    if not interaction.guild:
        await interaction.response.send_message("This command must be used in a server.", ephemeral=True); return
    state = guild_state(interaction.guild.id); state["ai_enabled"] = ai_enabled; save_state(STATE)
    await interaction.response.send_message(f"⚙️ AI is now **{'enabled' if ai_enabled else 'disabled'}** for this server.", ephemeral=True)


@bot.tree.command(name="stats", description="Show Forge usage statistics.")
async def stats(interaction: discord.Interaction):
    total = sum(int(v) for v in STATE.get("usage", {}).values())
    mine = int(STATE.get("usage", {}).get(str(interaction.user.id), 0))
    await interaction.response.send_message(f"📊 **ESN Forge Stats**\nYour commands: **{mine}**\nTracked commands: **{total}**\nGuilds: **{len(bot.guilds)}**", ephemeral=True)


@bot.tree.command(name="health", description="Run a local Forge health check.")
async def health(interaction: discord.Interaction):
    checks = [
        ("Discord connection", bot.is_ready()),
        ("OpenAI configured", bool(os.getenv("OPENAI_API_KEY", "").strip())),
        ("State storage", DATA_FILE.parent.exists()),
    ]
    await interaction.response.send_message("**Forge Health**\n" + "\n".join(f"{'✅' if ok else '❌'} {name}" for name, ok in checks), ephemeral=True)


@bot.tree.command(name="color", description="Validate a hex color and show its integer value.")
async def color(interaction: discord.Interaction, value: str):
    try: parsed = hex_color(value)
    except ValueError as exc:
        await interaction.response.send_message(str(exc), ephemeral=True); return
    await interaction.response.send_message(f"🎨 `{value.upper()}` → decimal `{parsed}`", ephemeral=True)


@bot.tree.command(name="uuid", description="Generate a UUID4.")
async def make_uuid(interaction: discord.Interaction):
    await interaction.response.send_message(f"`{uuid.uuid4()}`", ephemeral=True)


@bot.tree.command(name="base64", description="Encode or decode Base64 text.")
@app_commands.describe(action="encode or decode", text="Text")
async def base64_tool(interaction: discord.Interaction, action: str, text: str):
    try:
        if action.lower() == "encode": result = base64.b64encode(text.encode()).decode()
        elif action.lower() == "decode": result = base64.b64decode(text.encode(), validate=True).decode()
        else: raise ValueError("Action must be encode or decode.")
        await interaction.response.send_message(f"```\n{result[:1800]}\n```", ephemeral=True)
    except Exception as exc:
        await interaction.response.send_message(f"❌ {exc}", ephemeral=True)


@bot.tree.command(name="regex", description="Test a regular expression against text.")
async def regex_tool(interaction: discord.Interaction, pattern: str, text: str):
    try:
        matches = re.findall(pattern, text)
        await interaction.response.send_message(f"Matches: **{len(matches)}**\n" + "\n".join(f"• `{str(x)[:200]}`" for x in matches[:15]), ephemeral=True)
    except re.error as exc:
        await interaction.response.send_message(f"❌ Invalid regex: {exc}", ephemeral=True)


@bot.tree.command(name="timestamp", description="Generate a Discord timestamp from a Unix time.")
async def timestamp(interaction: discord.Interaction, unix: int):
    await interaction.response.send_message(f"`<t:{unix}:F>`  `<t:{unix}:R>`", ephemeral=True)


@bot.tree.command(name="deploy-check", description="Check whether Forge is configured for deployment.")
async def deploy_check(interaction: discord.Interaction):
    if interaction.user.id not in owners():
        await interaction.response.send_message("Owner only.", ephemeral=True); return
    await interaction.response.send_message("**Deployment Check**\n" + "\n".join([
        "✅ Discord token loaded",
        f"{'✅' if os.getenv('OPENAI_API_KEY') else '⚠️'} OpenAI key {'loaded' if os.getenv('OPENAI_API_KEY') else 'not configured'}",
        f"✅ Connected to {len(bot.guilds)} guild(s)",
        "✅ Self-contained bot.py architecture",
    ]), ephemeral=True)


@bot.tree.command(name="shutdown", description="Safely shut Forge down.")
async def shutdown(interaction: discord.Interaction):
    if interaction.user.id not in owners():
        await interaction.response.send_message("Owner only.", ephemeral=True); return
    await interaction.response.send_message("🛑 ESN Forge shutting down.", ephemeral=True)
    await bot.close()


@bot.tree.command(name="invite", description="Generate the bot invite URL.")
async def invite(interaction: discord.Interaction):
    if not bot.user:
        await interaction.response.send_message("Bot user is not ready yet.", ephemeral=True); return
    perms = discord.Permissions(administrator=True)
    url = discord.utils.oauth_url(bot.user.id, permissions=perms, scopes=("bot", "applications.commands"))
    await interaction.response.send_message(url, ephemeral=True)


@bot.event
async def on_app_command_error(interaction: discord.Interaction, error: app_commands.AppCommandError):
    log.exception("Slash command error", exc_info=error)
    message = "❌ Forge hit an error. Check the terminal for details."
    try:
        if interaction.response.is_done(): await interaction.followup.send(message, ephemeral=True)
        else: await interaction.response.send_message(message, ephemeral=True)
    except discord.HTTPException: pass


bot.run(TOKEN)
