import io
import zipfile
import discord
from discord import app_commands
from discord.ext import commands


def safe_name(value: str) -> str:
    cleaned = "".join(c.lower() if c.isalnum() else "-" for c in value.strip())
    return "-".join(x for x in cleaned.split("-") if x)[:40] or "discord-bot"


def make_project(name: str, language: str, features: list[str]) -> bytes:
    slug = safe_name(name)
    feature_text = ", ".join(features) or "slash commands"
    if language == "python":
        files = {
            "bot.py": '''import os\nimport discord\nfrom discord.ext import commands\nfrom dotenv import load_dotenv\n\nload_dotenv()\n\nclass Bot(commands.Bot):\n    def __init__(self):\n        intents = discord.Intents.default()\n        intents.message_content = True\n        super().__init__(command_prefix="!", intents=intents)\n\n    async def setup_hook(self):\n        await self.tree.sync()\n\nbot = Bot()\n\n@bot.tree.command(name="ping", description="Check bot latency.")\nasync def ping(interaction: discord.Interaction):\n    await interaction.response.send_message(f"Pong! {round(bot.latency * 1000)}ms")\n\nbot.run(os.environ["DISCORD_TOKEN"])\n''',
            "requirements.txt": "discord.py>=2.5,<3\npython-dotenv>=1.0,<2\n",
            ".env.example": "DISCORD_TOKEN=\n",
            ".gitignore": ".env\n__pycache__/\n*.pyc\n",
            "README.md": f"# {name}\n\nGenerated by ESN Forge.\n\nFeatures requested: {feature_text}\n\n## Run\n1. Copy `.env.example` to `.env`.\n2. Add your bot token.\n3. Install requirements.\n4. Run `python bot.py`.\n\nNever commit `.env` or bot tokens.\n",
        }
    else:
        files = {
            "index.js": '''const {{ Client, GatewayIntentBits, REST, Routes }} = require("discord.js");\nrequire("dotenv").config();\n\nconst client = new Client({ intents: [GatewayIntentBits.Guilds] });\nclient.once("ready", () => console.log(`Logged in as ${client.user.tag}`));\nclient.login(process.env.DISCORD_TOKEN);\n''',
            "package.json": '''{\n  "name": "discord-bot",\n  "version": "1.0.0",\n  "private": true,\n  "scripts": {"start": "node index.js"},\n  "dependencies": {"discord.js": "^14.0.0", "dotenv": "^16.0.0"}\n}\n''',
            ".env.example": "DISCORD_TOKEN=\n",
            ".gitignore": ".env\nnode_modules/\n",
            "README.md": f"# {name}\n\nGenerated by ESN Forge.\n\nFeatures requested: {feature_text}\n\nRun `npm install`, configure `.env`, then `npm start`.\nNever commit `.env`.\n",
        }
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for path, content in files.items():
            archive.writestr(f"{slug}/{path}", content)
        archive.writestr(f"{slug}/FORGE-MANIFEST.txt", f"ESN Forge project\nName: {name}\nLanguage: {language}\nFeatures: {feature_text}\n")
    buffer.seek(0)
    return buffer.read()


class BotBuilder(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @app_commands.command(name="bot", description="Generate a downloadable Discord bot project.")
    @app_commands.describe(name="Bot/project name", language="Python or JavaScript", features="Comma-separated features")
    @app_commands.choices(language=[
        app_commands.Choice(name="Python (discord.py)", value="python"),
        app_commands.Choice(name="JavaScript (discord.js)", value="javascript"),
    ])
    async def bot_builder(self, interaction: discord.Interaction, name: str, language: app_commands.Choice[str], features: str = "slash commands, embeds, logging"):
        feature_list = [x.strip() for x in features.split(",") if x.strip()][:15]
        data = make_project(name[:80], language.value, feature_list)
        file = discord.File(io.BytesIO(data), filename=f"{safe_name(name)}-esn-forge.zip")
        embed = discord.Embed(title="🤖 Bot Forge", description=f"Generated **{name[:80]}** as a real starter project.", color=0x6366F1)
        embed.add_field(name="Runtime", value="discord.py" if language.value == "python" else "discord.js", inline=True)
        embed.add_field(name="Features", value=", ".join(feature_list)[:1000] or "slash commands", inline=True)
        embed.add_field(name="Security", value="Secrets stay in environment variables; `.env` is ignored by Git.", inline=False)
        await interaction.response.send_message(embed=embed, file=file)


async def setup(bot):
    await bot.add_cog(BotBuilder(bot))
