import io
import json
import zipfile

import discord
from discord import app_commands
from discord.ext import commands

from utils.validation import clean_csv, safe_slug


def py_project(name: str, features: list[str]) -> dict[str, str]:
    commands_code = []
    for feature in features:
        key = safe_slug(feature, "feature").replace("-", "_")
        commands_code.append(
            f'@bot.tree.command(name="{key}", description="Generated Forge command")\n'
            f'async def {key}(interaction: discord.Interaction):\n'
            f'    await interaction.response.send_message({feature[:150]!r})\n'
        )
    return {
        "bot.py": (
            'import os\nimport discord\nfrom discord.ext import commands\nfrom dotenv import load_dotenv\n\n'
            'load_dotenv()\n\n'
            'class ForgeBot(commands.Bot):\n'
            '    def __init__(self):\n'
            '        intents = discord.Intents.default()\n'
            '        super().__init__(command_prefix="!", intents=intents)\n\n'
            '    async def setup_hook(self):\n'
            '        await self.tree.sync()\n\n'
            'bot = ForgeBot()\n\n'
            + '\n'.join(commands_code)
            + '\n\nif __name__ == "__main__":\n'
            '    bot.run(os.environ["DISCORD_TOKEN"])\n'
        ),
        "requirements.txt": "discord.py>=2.5,<3\npython-dotenv>=1.0,<2\n",
        ".env.example": "DISCORD_TOKEN=\n",
        ".gitignore": ".env\n__pycache__/\n*.py[cod]\n",
        "README.md": f"# {name}\n\nDiscord bot generated by ESN Forge.\n\nFeatures: {', '.join(features) or 'slash commands'}\n\n## Setup\n1. Copy `.env.example` to `.env`.\n2. Add your Discord bot token.\n3. Install with `pip install -r requirements.txt`.\n4. Run `python bot.py`.\n\nNever commit secrets.\n",
    }


def js_project(name: str, features: list[str]) -> dict[str, str]:
    commands_code = []
    for feature in features:
        key = safe_slug(feature, "feature").replace("-", "_")
        commands_code.append(
            f'async function {key}(interaction) {{ await interaction.reply({json.dumps(feature[:150])}); }}'
        )
    return {
        "index.js": (
            'require("dotenv").config();\n'
            'const { Client, GatewayIntentBits } = require("discord.js");\n'
            'const client = new Client({ intents: [GatewayIntentBits.Guilds] });\n'
            'client.once("ready", () => console.log(`Logged in as ${client.user.tag}`));\n'
            + '\n'.join(commands_code)
            + '\nclient.login(process.env.DISCORD_TOKEN);\n'
        ),
        "package.json": json.dumps(
            {
                "name": safe_slug(name),
                "version": "1.0.0",
                "private": True,
                "scripts": {"start": "node index.js"},
                "dependencies": {"discord.js": "^14.0.0", "dotenv": "^16.0.0"},
            },
            indent=2,
        ) + "\n",
        ".env.example": "DISCORD_TOKEN=\n",
        ".gitignore": ".env\nnode_modules/\n",
        "README.md": f"# {name}\n\nDiscord bot generated by ESN Forge.\n\nFeatures: {', '.join(features) or 'slash commands'}\n\nRun `npm install`, configure `.env`, then `npm start`.\n",
    }


def make_project(name: str, language: str, features: list[str]) -> bytes:
    slug = safe_slug(name)
    files = py_project(name, features) if language == "python" else js_project(name, features)
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for path, content in files.items():
            archive.writestr(f"{slug}/{path}", content)
        archive.writestr(
            f"{slug}/FORGE-MANIFEST.json",
            json.dumps(
                {"generator": "ESN Forge", "name": name, "language": language, "features": features},
                indent=2,
            ),
        )
    return buffer.getvalue()


class BotBuilder(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @app_commands.command(name="bot", description="Generate a downloadable Discord bot project.")
    @app_commands.describe(
        name="Project name",
        language="Python or JavaScript",
        features="Comma-separated feature/command names",
    )
    @app_commands.choices(
        language=[
            app_commands.Choice(name="Python (discord.py)", value="python"),
            app_commands.Choice(name="JavaScript (discord.js)", value="javascript"),
        ]
    )
    async def generate_bot(
        self,
        interaction: discord.Interaction,
        name: str,
        language: app_commands.Choice[str],
        features: str = "ping, help, moderation",
    ):
        feature_list = clean_csv(features, 15)
        data = make_project(name[:80], language.value, feature_list)
        file = discord.File(io.BytesIO(data), filename=f"{safe_slug(name)}-esn-forge.zip")
        embed = discord.Embed(
            title="🤖 Bot Forge",
            description=f"Generated **{name[:80]}** with {len(feature_list)} requested features.",
            color=0x6366F1,
        )
        embed.add_field(name="Runtime", value="discord.py" if language.value == "python" else "discord.js")
        embed.add_field(
            name="Included",
            value="ZIP project + README + manifest + secret-safe environment template",
            inline=False,
        )
        await interaction.response.send_message(embed=embed, file=file)


async def setup(bot):
    await bot.add_cog(BotBuilder(bot))
