import ast
import base64
import hashlib
import io
import json
import os
import re
import uuid
import zipfile
from datetime import datetime, timezone
from pathlib import PurePosixPath

import discord
from discord import app_commands
from discord.ext import commands


MAX_TEXT = 3800


def clip(text: str, limit: int = 1800) -> str:
    text = str(text)
    return text if len(text) <= limit else text[: max(0, limit - 3)] + "..."


def code_block(text: str, language: str = "text") -> str:
    return f"```{language}\n{clip(text, 1700)}\n```"


def safe_project_name(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._ -]", "", name).strip().replace(" ", "-")
    return cleaned[:48] or "forge-project"


def command_identifier(name: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9_ -]", "", name).strip().lower().replace(" ", "_").replace("-", "_")
    return value or "forge_command"


def validate_hex(value: str) -> str | None:
    value = value.strip().lstrip("#")
    return value.upper() if re.fullmatch(r"[0-9A-Fa-f]{6}", value) else None


def parse_owner_ids() -> set[int]:
    return {int(x.strip()) for x in os.getenv("OWNER_IDS", "").split(",") if x.strip().isdigit()}


def make_bot_project(name: str, language: str, features: list[str]) -> tuple[bytes, str]:
    project = safe_project_name(name)
    feature_text = ", ".join(features) if features else "slash commands"
    files: dict[str, str] = {
        "README.md": (
            f"# {name}\n\nGenerated by ESN Forge.\n\n"
            f"## Features\n{chr(10).join(f'- {item}' for item in (features or ['slash commands']))}\n\n"
            "## Configuration\nCopy `.env.example` to `.env` and add your Discord token. "
            "Never commit `.env`.\n"
        ),
        ".gitignore": ".env\n__pycache__/\n*.py[cod]\nnode_modules/\n",
        ".env.example": "DISCORD_TOKEN=replace_with_your_bot_token\n",
    }
    if language == "python":
        files["bot.py"] = '''import os\n\nimport discord\nfrom discord import app_commands\nfrom discord.ext import commands\nfrom dotenv import load_dotenv\n\nload_dotenv()\nTOKEN = os.getenv("DISCORD_TOKEN")\nif not TOKEN:\n    raise RuntimeError("DISCORD_TOKEN is missing")\n\nintents = discord.Intents.default()\nbot = commands.Bot(command_prefix="!", intents=intents)\n\n@bot.event\nasync def on_ready():\n    await bot.tree.sync()\n    print(f"Online as {bot.user} in {len(bot.guilds)} guild(s)")\n\n@bot.tree.command(name="ping", description="Check bot latency")\nasync def ping(interaction: discord.Interaction):\n    await interaction.response.send_message(f"Pong! {round(bot.latency * 1000)}ms")\n\nbot.run(TOKEN)\n'''
        files["requirements.txt"] = "discord.py>=2.5,<3\npython-dotenv>=1.0,<2\n"
    else:
        files["index.js"] = '''require("dotenv").config();\nconst { Client, GatewayIntentBits, REST, Routes, SlashCommandBuilder } = require("discord.js");\n\nconst token = process.env.DISCORD_TOKEN;\nif (!token) throw new Error("DISCORD_TOKEN is missing");\n\nconst client = new Client({ intents: [GatewayIntentBits.Guilds] });\nconst commands = [new SlashCommandBuilder().setName("ping").setDescription("Check bot latency")].map(c => c.toJSON());\n\nclient.once("ready", () => console.log(`Online as ${client.user.tag}`));\nclient.on("interactionCreate", async interaction => {\n  if (!interaction.isChatInputCommand()) return;\n  if (interaction.commandName === "ping") await interaction.reply(`Pong! ${client.ws.ping}ms`);\n});\n\nclient.login(token);\n'''
        files["package.json"] = json.dumps({"private": True, "dependencies": {"discord.js": "^14.0.0", "dotenv": "^16.0.0"}}, indent=2) + "\n"
    files["FORGE-MANIFEST.json"] = json.dumps({"generator": "ESN Forge", "project": name, "language": language, "features": features, "generated_at": datetime.now(timezone.utc).isoformat()}, indent=2) + "\n"
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as archive:
        for path, content in files.items():
            archive.writestr(f"{project}/{path}", content)
    return buf.getvalue(), project


def static_review(source: str) -> list[tuple[str, str]]:
    findings: list[tuple[str, str]] = []
    checks = [
        (r"(?:DISCORD_TOKEN|OPENAI_API_KEY|API_KEY)\s*=\s*['\"][^'\"]+['\"]", "high", "Hard-coded credential detected. Move secrets to environment variables."),
        (r"\b(?:eval|exec)\s*\(", "high", "Dynamic code execution detected. Do not pass untrusted input to eval/exec."),
        (r"except\s*:", "medium", "Bare exception handler detected. Catch specific exceptions and log the failure."),
        (r"subprocess\.(?:run|Popen|call)\([^\n]*shell\s*=\s*True", "high", "Shell execution with shell=True needs strict input validation."),
        (r"verify\s*=\s*False", "high", "TLS certificate verification is disabled."),
        (r"password\s*=\s*['\"]", "high", "Possible hard-coded password detected."),
    ]
    for pattern, severity, message in checks:
        if re.search(pattern, source, re.IGNORECASE):
            findings.append((severity, message))
    if not source.strip():
        findings.append(("medium", "No source code was provided."))
        return findings
    try:
        tree = ast.parse(source)
        function_count = sum(isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) for n in ast.walk(tree))
        class_count = sum(isinstance(n, ast.ClassDef) for n in ast.walk(tree))
        if function_count > 25:
            findings.append(("low", f"Large module: {function_count} functions detected. Consider splitting responsibilities."))
        if class_count > 15:
            findings.append(("low", f"Large module: {class_count} classes detected. Consider separating domains."))
    except SyntaxError as exc:
        findings.append(("high", f"Python syntax error at line {exc.lineno}: {exc.msg}"))
    if not findings:
        findings.append(("good", "No obvious high-risk patterns were detected by the static review."))
    return findings


class Tools(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    async def _owner(self, interaction: discord.Interaction) -> bool:
        if interaction.user.id not in parse_owner_ids():
            await interaction.response.send_message("⛔ This is an owner-only Forge command.", ephemeral=True)
            return False
        return True

    @app_commands.command(name="about", description="Learn about ESN Forge.")
    async def about(self, interaction):
        embed = discord.Embed(title="⚒️ ESN Forge", description="Build. Create. Deploy.", color=0x42E8F4)
        embed.add_field(name="Developer toolkit", value="Generate Discord bots, inspect code, build embeds, plan servers, debug projects, and create downloadable starter projects.", inline=False)
        embed.add_field(name="Security", value="Forge is designed to keep credentials out of generated projects and Git history.", inline=False)
        await interaction.response.send_message(embed=embed)

    @app_commands.command(name="ping", description="Check Forge latency.")
    async def ping(self, interaction):
        await interaction.response.send_message(f"🏓 Pong! `{round(self.bot.latency * 1000)}ms`", ephemeral=True)

    @app_commands.command(name="explain", description="Explain code or a programming concept.")
    @app_commands.describe(code_or_topic="Code, error, or concept to explain")
    async def explain(self, interaction, code_or_topic: str):
        source = code_or_topic.strip()
        if not source:
            await interaction.response.send_message("❌ Give me code, an error, or a programming concept.", ephemeral=True)
            return
        findings = static_review(source)
        severity = "high" if any(level == "high" for level, _ in findings) else "normal"
        embed = discord.Embed(title="📖 Forge Explain", description=clip(source, 900), color=0x6366F1)
        embed.add_field(name="Quick analysis", value="\n".join(f"• {message}" for _, message in findings[:5]), inline=False)
        embed.add_field(name="Next step", value="For a full natural-language explanation, use `/ask` with the code and what you want explained." if severity == "normal" else "Fix the flagged security/syntax issue before relying on this code.", inline=False)
        await interaction.response.send_message(embed=embed)

    @app_commands.command(name="improve", description="Analyze code and return concrete refactoring targets.")
    @app_commands.describe(code="Code to improve")
    async def improve(self, interaction, code: str):
        findings = static_review(code)
        suggestions = [message for level, message in findings if level != "good"]
        suggestions += [
            "Keep functions focused on one responsibility.",
            "Validate external/user input before using it.",
            "Add tests around failure paths and permissions.",
            "Use structured logging instead of print for production diagnostics.",
        ]
        embed = discord.Embed(title="✨ Forge Improve", description="\n".join(f"• {clip(x, 500)}" for x in suggestions[:8]), color=0x7DEFF2)
        await interaction.response.send_message(embed=embed)

    @app_commands.command(name="review", description="Run a static security and quality review.")
    @app_commands.describe(code="Paste the code to review")
    async def review(self, interaction, code: str):
        findings = static_review(code)
        labels = {"high": "🔴 HIGH", "medium": "🟠 MEDIUM", "low": "🟡 LOW", "good": "🟢 GOOD"}
        text = "\n".join(f"{labels[level]} — {message}" for level, message in findings)
        await interaction.response.send_message(embed=discord.Embed(title="🔎 Forge Review", description=clip(text, 3600), color=0x168CFF))

    @app_commands.command(name="convert", description="Prepare a safe conversion plan between languages.")
    @app_commands.describe(code="Source code", target="Target language")
    async def convert(self, interaction, code: str, target: str):
        target_clean = target.strip()[:40] or "target language"
        source_lang = "Python" if re.search(r"\bdef\s+\w+\s*\(", code) else "JavaScript" if "const " in code or "=>" in code else "unknown"
        plan = [f"Detected source: **{source_lang}**", f"Target: **{target_clean}**", "Map types and data structures", "Replace standard-library/API calls with target equivalents", "Preserve validation, error handling, and async behavior", "Run syntax checks and behavior tests against representative inputs"]
        await interaction.response.send_message(embed=discord.Embed(title="🔄 Forge Convert", description="\n".join(f"• {x}" for x in plan), color=0x6366F1))

    @app_commands.command(name="docs", description="Generate a useful documentation skeleton.")
    @app_commands.describe(target="Function, class, module, or project name")
    async def docs(self, interaction, target: str):
        name = target.strip()[:100] or "Project"
        text = f"# {name}\n\n## Purpose\nDescribe what this component does.\n\n## Usage\n```text\nShow the smallest useful example.\n```\n\n## Parameters\n- `name`: type — description\n\n## Returns\nDescribe the output and important states.\n\n## Errors\nDocument expected failures and recovery behavior.\n\n## Security\nDocument permissions, secrets, validation, and trust boundaries.\n\n## Testing\nList unit, integration, and failure-path tests."
        await interaction.response.send_message(code_block(text, "md"))

    @app_commands.command(name="generate", description="Generate a non-empty starter implementation.")
    @app_commands.describe(request="What you want to build", language="Python, JavaScript, or HTML")
    async def generate(self, interaction, request: str, language: str = "Python"):
        request = request.strip()
        if not request:
            await interaction.response.send_message("❌ Describe what you want generated.", ephemeral=True)
            return
        lang = language.lower().strip()
        if lang in ("python", "py"):
            output = f'''"""ESN Forge generated module.\nRequest: {request[:500]}\n"""\n\ndef main() -> None:\n    print("Forge project initialized")\n\n\nif __name__ == "__main__":\n    main()\n'''
            syntax = "python"
        elif lang in ("javascript", "js", "node", "node.js"):
            output = f'''// ESN Forge generated module.\n// Request: {request[:500]}\n\nfunction main() {{\n  console.log("Forge project initialized");\n}}\n\nmain();\n'''
            syntax = "js"
        else:
            output = f'''<!doctype html>\n<html lang="en">\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Forge Project</title></head>\n<body><main><h1>Forge Project</h1><p>{clip(request, 400)}</p></main></body>\n</html>'''
            syntax = "html"
        await interaction.response.send_message(code_block(output, syntax))

    @app_commands.command(name="json", description="Validate and format JSON.")
    @app_commands.describe(data="JSON text")
    async def json_tool(self, interaction, data: str):
        try:
            parsed = json.loads(data)
        except json.JSONDecodeError as exc:
            await interaction.response.send_message(f"❌ Invalid JSON: `{exc.msg}` at position `{exc.pos}`", ephemeral=True)
            return
        await interaction.response.send_message(code_block(json.dumps(parsed, indent=2, ensure_ascii=False), "json"))

    @app_commands.command(name="regex", description="Validate a regular expression and show basic metadata.")
    @app_commands.describe(pattern="Regex pattern")
    async def regex(self, interaction, pattern: str):
        try:
            compiled = re.compile(pattern)
        except re.error as exc:
            await interaction.response.send_message(f"❌ Invalid regex: `{exc}`", ephemeral=True)
            return
        await interaction.response.send_message(f"🧩 Regex is **valid**. Groups: `{compiled.groups}`. Named groups: `{len(compiled.groupindex)}`.")

    @app_commands.command(name="timestamp", description="Create Discord timestamps from Unix time.")
    @app_commands.describe(unix="Unix timestamp")
    async def timestamp(self, interaction, unix: int):
        try:
            datetime.fromtimestamp(unix, tz=timezone.utc)
        except (OverflowError, OSError, ValueError):
            await interaction.response.send_message("❌ That Unix timestamp is out of range.", ephemeral=True)
            return
        await interaction.response.send_message(f"Discord timestamp: `<t:{unix}:F>`\nRelative: `<t:{unix}:R>`")

    @app_commands.command(name="color", description="Inspect a hex color.")
    @app_commands.describe(hex_value="Six-digit hex color")
    async def color(self, interaction, hex_value: str):
        value = validate_hex(hex_value)
        if not value:
            await interaction.response.send_message("❌ Use a six-digit color such as `#42E8F4`.", ephemeral=True)
            return
        r, g, b = int(value[:2], 16), int(value[2:4], 16), int(value[4:], 16)
        await interaction.response.send_message(f"🎨 `#{value}` → RGB `{r}, {g}, {b}` → Decimal `{int(value, 16)}`")

    @app_commands.command(name="base64", description="Encode or decode Base64 text.")
    @app_commands.describe(action="encode or decode", text="Text to process")
    @app_commands.choices(action=[app_commands.Choice(name="Encode", value="encode"), app_commands.Choice(name="Decode", value="decode")])
    async def base64_tool(self, interaction, action: str, text: str):
        try:
            if action == "encode":
                result = base64.b64encode(text.encode()).decode()
            else:
                result = base64.b64decode(text.encode(), validate=True).decode()
        except (ValueError, UnicodeDecodeError):
            await interaction.response.send_message("❌ Invalid Base64 input.", ephemeral=True)
            return
        await interaction.response.send_message(code_block(result))

    @app_commands.command(name="uuid", description="Generate a UUID4.")
    async def uuid_tool(self, interaction):
        await interaction.response.send_message(f"`{uuid.uuid4()}`")

    @app_commands.command(name="hash", description="Hash text with SHA-256.")
    @app_commands.describe(text="Text to hash")
    async def hash_tool(self, interaction, text: str):
        digest = hashlib.sha256(text.encode()).hexdigest()
        await interaction.response.send_message(f"SHA-256:\n`{digest}`")

    @app_commands.command(name="permissions", description="Inspect Forge's permissions in this server.")
    async def permissions(self, interaction):
        if not interaction.guild:
            await interaction.response.send_message("This command must be used in a server.", ephemeral=True)
            return
        me = interaction.guild.me
        if not me:
            await interaction.response.send_message("I couldn't resolve my member object.", ephemeral=True)
            return
        names = ["administrator", "manage_guild", "manage_channels", "manage_roles", "manage_webhooks", "send_messages", "embed_links", "attach_files"]
        text = "\n".join(f"• `{name}`: {'✅' if getattr(me.guild_permissions, name) else '❌'}" for name in names)
        await interaction.response.send_message(embed=discord.Embed(title="🔐 Forge Permissions", description=text, color=0x42E8F4))

    @app_commands.command(name="security-audit", description="Run a lightweight server security audit.")
    async def security_audit(self, interaction):
        if not interaction.guild:
            await interaction.response.send_message("Use this command in a server.", ephemeral=True)
            return
        guild = interaction.guild
        me = guild.me
        admin_roles = [role for role in guild.roles if role.permissions.administrator and not role.is_default()]
        checks = [
            ("2FA moderation requirement", guild.mfa_level.value == 1),
            ("Bot member resolved", me is not None),
            ("Administrator roles reviewed", len(admin_roles) <= 3),
            ("Owner resolved", guild.owner is not None),
        ]
        body = "\n".join(f"{'✅' if ok else '⚠️'} {label}" for label, ok in checks)
        body += f"\n\nAdministrator roles found: `{len(admin_roles)}`\nThis is a lightweight audit; review role hierarchy and channel overwrites manually."
        await interaction.response.send_message(embed=discord.Embed(title="🛡️ Forge Security Audit", description=body, color=0x168CFF))

    @app_commands.command(name="health", description="Check Forge runtime health.")
    async def health(self, interaction):
        await interaction.response.send_message(embed=discord.Embed(title="💚 Forge Health", description=f"Status: **Online**\nLatency: **{round(self.bot.latency * 1000)}ms**\nServers: **{len(self.bot.guilds)}**\nUTC: **{datetime.now(timezone.utc):%Y-%m-%d %H:%M:%S}**", color=0x42E8F4))

    @app_commands.command(name="logs", description="Show owner-only runtime diagnostics.")
    async def logs(self, interaction):
        if not await self._owner(interaction): return
        await interaction.response.send_message(f"📋 `{len(self.bot.guilds)}` guilds | `{round(self.bot.latency * 1000)}ms` latency | Python process online", ephemeral=True)

    @app_commands.command(name="bot-create", description="Create a downloadable Discord bot project.")
    @app_commands.describe(name="Project name", language="Python or JavaScript", features="Comma-separated features")
    async def create_bot(self, interaction, name: str, language: str = "Python", features: str = "slash commands"):
        language_value = language.lower().strip()
        if language_value in ("python", "py"):
            language_value = "python"
        elif language_value in ("javascript", "js", "node", "node.js"):
            language_value = "javascript"
        else:
            await interaction.response.send_message("❌ Language must be Python or JavaScript.", ephemeral=True)
            return
        feature_list = [item.strip() for item in features.split(",") if item.strip()][:20]
        data, filename = make_bot_project(name, language_value, feature_list)
        await interaction.response.send_message(f"🤖 **{name}** generated with `{len(feature_list) or 1}` feature entries.", file=discord.File(io.BytesIO(data), filename=f"{filename}.zip"))

    @app_commands.command(name="bot-command", description="Generate a real Discord slash-command implementation.")
    @app_commands.describe(name="Command name", language="Python or JavaScript")
    async def generate_bot_command(self, interaction, name: str, language: str = "Python"):
        cmd = command_identifier(name)[:32]
        if language.lower() in ("python", "py"):
            output = f'@bot.tree.command(name="{cmd}", description="Forge generated command")\nasync def {cmd}(interaction: discord.Interaction):\n    await interaction.response.send_message("Command /{cmd} executed successfully.")'
            lang = "python"
        else:
            output = f"const {{ SlashCommandBuilder }} = require('discord.js');\nmodule.exports = {{\n  data: new SlashCommandBuilder().setName('{cmd}').setDescription('Forge generated command'),\n  async execute(interaction) {{ await interaction.reply('Command /{cmd} executed successfully.'); }}\n}};"
            lang = "js"
        await interaction.response.send_message(code_block(output, lang))

    @app_commands.command(name="bot-event", description="Generate a real Discord bot event handler.")
    @app_commands.describe(event="ready, message, member_join, etc.", language="Python or JavaScript")
    async def generate_bot_event(self, interaction, event: str, language: str = "Python"):
        event_key = re.sub(r"[^a-zA-Z0-9_]", "_", event.strip().lower()).strip("_") or "ready"
        known_python = {"ready": "on_ready", "message": "on_message", "member_join": "on_member_join", "member_remove": "on_member_remove", "interaction": "on_interaction"}
        python_event = known_python.get(event_key, f"on_{event_key}")
        if language.lower() in ("python", "py"):
            if python_event == "on_message":
                output = '@bot.event\nasync def on_message(message: discord.Message):\n    if message.author.bot:\n        return\n    await bot.process_commands(message)'
            elif python_event == "on_ready":
                output = '@bot.event\nasync def on_ready():\n    print(f"Online as {bot.user}")'
            else:
                output = f'@bot.event\nasync def {python_event}(*args):\n    # Implement your {event_key} behavior here.\n    return'
            lang = "python"
        else:
            js_event = event_key if event_key != "member_join" else "guildMemberAdd"
            output = f"client.on('{js_event}', async (...args) => {{\n  // Implement your {event_key} behavior here.\n}});"
            lang = "js"
        await interaction.response.send_message(code_block(output, lang))

    @app_commands.command(name="bot-feature", description="Create an implementation plan for a bot feature.")
    @app_commands.describe(feature="Feature you want to build")
    async def plan_bot_feature(self, interaction, feature: str):
        name = feature.strip()[:120] or "new feature"
        plan = ["Define user-visible behavior", "Choose commands/events and required intents", "Define permission checks and trust boundaries", "Choose persistent state and schema if needed", "Implement success + failure paths", "Add rate limits and logging", "Add unit/integration tests", "Deploy with secrets outside source control"]
        await interaction.response.send_message(embed=discord.Embed(title="🤖 Bot Feature Forge", description=f"**Feature:** {name}\n\n" + "\n".join(f"`{i}` {item}" for i, item in enumerate(plan, 1)), color=0x6366F1))

    @app_commands.command(name="bot-structure", description="Generate a production-oriented Discord bot structure.")
    async def show_bot_structure(self, interaction):
        tree = "bot.py\ncogs/\n  commands.py\n  events.py\n  moderation.py\n  admin.py\nutils/\n  database.py\n  permissions.py\n  logging.py\ntests/\n.env.example\n.gitignore\nrequirements.txt\nREADME.md"
        await interaction.response.send_message(code_block(tree, "text"))

    @app_commands.command(name="bot-config", description="Show secure bot configuration requirements.")
    async def show_bot_config(self, interaction):
        await interaction.response.send_message("⚙️ Required configuration: `DISCORD_TOKEN` in a secret/environment variable. Optional API keys belong in the host secret manager. `.env` must stay ignored and must never be committed.", ephemeral=True)

    @app_commands.command(name="bot-export", description="Export a complete default Forge bot project.")
    async def export_bot(self, interaction):
        data, filename = make_bot_project("ForgeBot", "python", ["slash commands", "secure configuration", "health check"])
        await interaction.response.send_message("📦 Default ForgeBot project exported.", file=discord.File(io.BytesIO(data), filename=f"{filename}.zip"))

    @app_commands.command(name="embed-json", description="Generate Discord-compatible embed JSON.")
    @app_commands.describe(title="Title", description="Description", footer="Footer")
    async def embed_json(self, interaction, title: str, description: str, footer: str = ""):
        data = {"title": title, "description": description}
        if footer.strip(): data["footer"] = {"text": footer.strip()}
        await interaction.response.send_message(code_block(json.dumps(data, indent=2, ensure_ascii=False), "json"))

    @app_commands.command(name="embed-code", description="Generate Python Discord embed code.")
    @app_commands.describe(title="Embed title", description="Embed description")
    async def embed_code(self, interaction, title: str, description: str):
        output = f"embed = discord.Embed(title={title!r}, description={description!r}, color=0x42E8F4)\nawait interaction.response.send_message(embed=embed)"
        await interaction.response.send_message(code_block(output, "python"))

    @app_commands.command(name="embed-template", description="Create a reusable embed template.")
    @app_commands.describe(kind="announcement, rules, welcome, update")
    async def embed_template(self, interaction, kind: str):
        templates = {"announcement": ("📢 Announcement", "Important update goes here."), "rules": ("📜 Rules", "Please follow the server rules."), "welcome": ("👋 Welcome", "Welcome to the community!"), "update": ("🔔 Update", "A new update is now available.")}
        title, description = templates.get(kind.strip().lower(), ("📌 Template", "Your content here."))
        await interaction.response.send_message(embed=discord.Embed(title=title, description=description, color=0x42E8F4))

    @app_commands.command(name="server-plan", description="Build a server architecture plan.")
    @app_commands.describe(theme="Server theme", size="small, medium, or large")
    async def server_plan(self, interaction, theme: str, size: str = "medium"):
        size_key = size.strip().lower()
        if size_key not in {"small", "medium", "large"}: size_key = "medium"
        community = ["general", "media", "gaming", "suggestions"]
        if size_key == "small": community = ["general", "support"]
        elif size_key == "large": community += ["clips", "off-topic", "events", "showcase"]
        channels = ["START HERE", "announcements", "rules", *community, "support", "staff-chat", "logs"]
        roles = ["Owner", "Administrator", "Moderator", "Staff", "Member", "Bot"]
        description = f"Theme: **{clip(theme, 80)}**\nSize: **{size_key}**\n\n**Channels**\n" + "\n".join(f"• {x}" for x in channels) + "\n\n**Roles**\n" + " → ".join(roles)
        await interaction.response.send_message(embed=discord.Embed(title="🏗️ Server Plan", description=clip(description, 3800), color=0x6366F1))

    @app_commands.command(name="server-roles", description="Generate a safe server role hierarchy.")
    async def server_roles(self, interaction):
        await interaction.response.send_message("👑 Owner\n🛡 Administrator\n🔨 Moderator\n🧰 Staff\n⭐ VIP/Creator\n👤 Member\n🤖 Bot")

    @app_commands.command(name="server-channels", description="Generate a server channel structure.")
    async def server_channels(self, interaction):
        await interaction.response.send_message(code_block("START HERE\n├─ announcements\n├─ rules\n└─ faq\n\nCOMMUNITY\n├─ general\n├─ media\n├─ gaming\n└─ suggestions\n\nSUPPORT\n├─ help\n└─ tickets\n\nSTAFF\n├─ staff-chat\n├─ logs\n└─ applications"))

    @app_commands.command(name="server-permissions", description="Show a least-privilege permission design.")
    async def server_permissions(self, interaction):
        await interaction.response.send_message("🔐 **Least privilege**\n• Owner: full control\n• Administrators: only trusted operational staff\n• Moderators: moderation actions, not server ownership powers\n• Staff: support channels only\n• @everyone: normal community access\n• Bots: only permissions their features require\n• Staff channels: deny @everyone explicitly")

    @app_commands.command(name="server-rules", description="Generate a server rules template.")
    async def server_rules(self, interaction):
        await interaction.response.send_message(code_block("1. Respect everyone.\n2. No harassment, threats, or targeted abuse.\n3. No spam, malicious links, or scams.\n4. Use channels for their intended purpose.\n5. Follow Discord's Terms and Community Guidelines.\n6. Do not bypass moderation actions.\n7. Report problems through the designated support channel.", "md"))

    @app_commands.command(name="server-audit", description="Audit basic server structure.")
    async def server_audit(self, interaction):
        if not interaction.guild:
            await interaction.response.send_message("Use this command in a server.", ephemeral=True)
            return
        guild = interaction.guild
        admins = sum(1 for role in guild.roles if role.permissions.administrator and not role.is_default())
        embed = discord.Embed(title="🔍 Server Audit", color=0x168CFF)
        embed.add_field(name="Members", value=str(guild.member_count), inline=True)
        embed.add_field(name="Channels", value=str(len(guild.channels)), inline=True)
        embed.add_field(name="Roles", value=str(len(guild.roles)), inline=True)
        embed.add_field(name="Administrator roles", value=str(admins), inline=True)
        embed.add_field(name="Owner", value=str(guild.owner) if guild.owner else "Unknown", inline=False)
        embed.add_field(name="Next checks", value="Review role hierarchy, channel overwrites, bot permissions, verification, and audit-log activity.", inline=False)
        await interaction.response.send_message(embed=embed)

    @app_commands.command(name="server-setup", description="Preview a safe server setup plan without changing anything.")
    async def server_setup(self, interaction):
        await interaction.response.send_message("🧪 **Dry run**\nNo server changes were made. A future deployment command should show the complete diff, require confirmation, and refuse destructive operations by default.", ephemeral=True)

    @app_commands.command(name="stats", description="Show Forge runtime statistics.")
    async def stats(self, interaction):
        await interaction.response.send_message(f"📊 **ESN Forge**\nServers: `{len(self.bot.guilds)}`\nLatency: `{round(self.bot.latency * 1000)}ms`\nLoaded commands: `{len(self.bot.tree.get_commands())}`", ephemeral=True)

    @app_commands.command(name="owner-status", description="Owner runtime status.")
    async def owner_status(self, interaction):
        if not await self._owner(interaction): return
        await interaction.response.send_message(f"👑 Online | guilds `{len(self.bot.guilds)}` | latency `{round(self.bot.latency * 1000)}ms`", ephemeral=True)

    @app_commands.command(name="owner-guilds", description="List guilds Forge is connected to.")
    async def owner_guilds(self, interaction):
        if not await self._owner(interaction): return
        lines = [f"• {g.name} (`{g.id}`)" for g in self.bot.guilds]
        await interaction.response.send_message(clip("\n".join(lines) or "No guilds.", 1900), ephemeral=True)

    @app_commands.command(name="owner-broadcast", description="Safely inspect broadcast capability status.")
    async def owner_broadcast(self, interaction):
        if not await self._owner(interaction): return
        await interaction.response.send_message("📡 Broadcast is disabled until a destination selector, permission check, rate limit, preview, and confirmation flow are enabled.", ephemeral=True)

    @app_commands.command(name="owner-maintenance", description="Show maintenance status.")
    async def owner_maintenance(self, interaction):
        if not await self._owner(interaction): return
        await interaction.response.send_message("🛠 Maintenance mode is controlled by the hosting process. Forge will not silently restart or mutate production configuration.", ephemeral=True)

    @app_commands.command(name="owner-shutdown", description="Show safe shutdown guidance.")
    async def owner_shutdown(self, interaction):
        if not await self._owner(interaction): return
        await interaction.response.send_message("⚠️ Use the hosting environment to stop Forge. This prevents an accidental chat-command outage.", ephemeral=True)


async def setup(bot):
    await bot.add_cog(Tools(bot))
